name: Build and Deploy

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: 14
      - name: Documents Sync
        run: |
          bash ./tools/build-docs.sh
      - name: install
        run: |
          npm install
      - name: Build
        run: |
          npm run build
          cp .asf.yaml build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
          publish_branch: asf-site
