name: Build and Deploy

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Documents Sync
        run: |
          bash ./tools/build-docs.sh
        shell: bash
      - name: install
        run: |
          cd ~/web
          npm install
      - name: Build
        run: |
          cd ~/web
          npm run build
      - name: Copy .asf.yaml
        run: |
          cp .asf.yaml ~/web/build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: web/build
          publish_branch: asf-site
